=== FURCAS-dev/FURCAS/moin/com.sap.tc.moin.libraries.base/schema/metamodel_inf.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:moinarch="http://sap.com/moin/MoinArchive"
	targetNamespace="http://sap.com/moin/MoinArchive">

	<xs:element name="Partitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="moinarch:Partition" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Partition">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="contentHash" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="DeploymentExtension">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ResourceBundle">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="FacilityId" type="xs:string"/>

	<xs:element name="MetamodelInf">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="moinarch:FacilityId" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="moinarch:DeploymentExtension" />
				<xs:element ref="moinarch:ResourceBundle" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="moinarch:Partitions" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== FURCAS-dev/FURCAS/ngpm/com.sap.ap.metamodel.core.epi/jmisrc/moin/reginfo/metamodel.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<MetamodelInf xmlns="http://sap.com/moin/MoinArchive"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://sap.com/moin/MoinArchive metamodel_inf.xsd">
  <FacilityId>PF</FacilityId>
  <DeploymentExtension class="com.sap.tc.moin.package6DBFA0FAF73913D04E1A01AB2E5C3D47D568CBAD.MetamodelExtension" />
  <Partitions>
    <Partition name="moin/meta/localization.moinmm"
      contentHash="9C78C891241A3E18F24908C8184FA2F5" />
    <Partition name="moin/meta/configuration.moinmm"
      contentHash="4B716A6F9EE7E03ADE647E4461BC46FC" />
    <Partition name="moin/meta/integration.moinmm"
      contentHash="46678603ADB9DA6C38776C88EE094BD0" />
    <Partition name="moin/meta/ui.moinmm"
      contentHash="C26BA17D21AA9ADDB2BD1B4F0DF2FD45" />
    <Partition name="moin/meta/persistence.moinmm"
      contentHash="6C21F774BFD02CF99B7265B7DDEEBF92" />
    <Partition name="moin/meta/abapMapping.moinmm"
      contentHash="230F1B3768890D864108A234F7027D8C" />
    <Partition name="moin/meta/dataaccess.moinmm"
      contentHash="F49048532A659DFFCA69EA3336E21FB1" />
    <Partition name="moin/meta/deployment.moinmm"
      contentHash="BAB8407D2EF272CF4C6479E180F6B28C" />
    <Partition name="moin/meta/behavioral.moinmm"
      contentHash="FA320AD0E8E8B138417243DD09C93253" />
    <Partition name="moin/meta/data.moinmm"
      contentHash="92F70EC423AAB8D0DECDD41E5BD48E31" />
    <Partition name="moin/meta/modelmanagement.moinmm"
      contentHash="90E0434FD007AE2812BEC6D66A9C0927" />
    <Partition name="moin/meta/ngpm.moinmm"
      contentHash="538AC241B85A16AD60CA89F7430286A4" />
  </Partitions>
</MetamodelInf>

=== FURCAS-dev/FURCAS/moin_tests/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/cpstest/metamodel.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<MetamodelInf xmlns="http://sap.com/moin/MoinArchive"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://sap.com/moin/MoinArchive metamodel_inf.xsd">
  <FacilityId>PF</FacilityId>
  <DeploymentExtension class="com.sap.tc.moin.package63449DD06F4F452037E675FD83797A4B78F083F4.MetamodelExtension" />
  <Partitions>
    <Partition name="moin/meta/toplevel2.moinmm"
      contentHash="1220510575453" />
    <Partition name="moin/meta/testcasesMofElement.moinmm"
      contentHash="1220510575484" />
    <Partition name="moin/meta/testcases.moinmm"
      contentHash="1220510575500" />
    <Partition name="moin/meta/toplevel3.moinmm"
      contentHash="1220510575468" />
    <Partition name="moin/meta/toplevel1.moinmm"
      contentHash="1220510575437" />
  </Partitions>
</MetamodelInf>
