=== FURCAS-dev/FURCAS/moin/com.sap.tc.moin.libraries.base/schema/modelcontentselection_inf.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:moinarch="http://sap.com/moin/MoinArchive"
	targetNamespace="http://sap.com/moin/MoinArchive">
	
	<xs:element name="ContentSelection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="moinarch:Property" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="Property">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="ModelContentSelectionInf">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="moinarch:SupportedContentSelectionTypes" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="SupportedContentSelectionTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="moinarch:ContentSelection" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== FURCAS-dev/FURCAS/moin/com.sap.tc.moin.metamodel.testcases/moin/reginfo/modelcontentselection.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<ModelContentSelectionInf xmlns="http://sap.com/moin/MoinArchive" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sap.com/moin/MoinArchive modelcontentselection_inf.xsd">
	<SupportedContentSelectionTypes>
		<ContentSelection type="DI" >
			<Property name="dcTypeName" value="com.sap.tc.moin.test.di.dctype.dummy.DummyTest" />
			<Property name="dcTypeVendor" value="test.sap.com" />
			<Property name="folder" value="src/models" /> 
			<Property name="folder" value="moin/models" />
			<Property name="folder" value="src/modeldata" /> 
		</ContentSelection >
		<ContentSelection type="DI" >
			<Property name="dcTypeName" value="com.sap.tc.moin.test.di.dctype.dummy.DummyTest" />
			<Property name="dcTypeVendor" value="test.sap.com" />
			<Property name="folder" value="src/mymodels" /> 
			<Property name="folder" value="moin/mymodels" /> 
		</ContentSelection >
		<ContentSelection type="DI" >
			<Property name="dcTypeName" value="com.sap.tc.moin.test.di.dctype.MoinTest" />
			<Property name="dcTypeVendor" value="test.sap.com" />
			<Property name="folder" value="src/addon/modeldata/" /> 			
		</ContentSelection >
	</SupportedContentSelectionTypes >
</ModelContentSelectionInf>
