=== FURCAS-dev/FURCAS/moin/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/src/com/sap/tc/moin/xm/test/pfl/xsd/ScenarioFlowDiagramReferencedContent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.sap.com/ScenarioFlowDiagramReferencedContent"
	xmlns:tns="http://www.sap.com/ScenarioFlowDiagramReferencedContent"
	elementFormDefault="qualified">
	<element name="ScenarioFlowDiagramReferencedContent" type="tns:ScenarioFlowDiagramReferencedContentType">
	</element>
	<complexType name="IDandTitleType">
		<sequence>
			<element name="Title" type="string" />
		</sequence>
		<attribute name="ID" type="string" />
		<attribute name="documentation" type="string"></attribute>
	</complexType>
	<complexType name="ScenarioFlowDiagramReferencedContentType">
		<sequence>
			<element name="RealizedBusinessScenario" type="tns:RealizedBusinessScenarioType"></element>
		</sequence>
	</complexType>
	<complexType name="RealizedBusinessScenarioType">
		<complexContent>
			<extension base="tns:IDandTitleType">
				<sequence>
					<element name="RealizedBusinessProcess" type="tns:RealizedBusinessProcessType"
						maxOccurs="unbounded" minOccurs="0">
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="RealizedBusinessProcessType">
		<complexContent>
			<extension base="tns:IDandTitleType">
				<sequence>
					<element name="RealizedBusinessProcessVariant" type="tns:IDandTitleType"
						maxOccurs="unbounded" minOccurs="0">
					</element>
					<element name="ProcessComponent" type="tns:ProcessComponentType"
						maxOccurs="1" minOccurs="1">
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<!--
		<complexType name="RealizedBusinessProcessVariantType"> <attribute
		name="name" type="string"></attribute> <attribute name="documentation"
		type="string"></attribute> <attribute name="id"
		type="string"></attribute> </complexType>
	-->
	<complexType name="ProcessComponentType">
		<complexContent>
			<extension base="tns:IDandTitleType">
				<sequence>
					<element name="DeploymentUnit" type="tns:IDandTitleType"
						maxOccurs="1" minOccurs="1">
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<!--
		<complexType name="DeploymentUnitType"> <attribute name="name"
		type="string"></attribute> <attribute name="documentation"
		type="string"></attribute> <attribute name="id"
		type="string"></attribute> </complexType>
	-->
</schema>

=== FURCAS-dev/FURCAS/moin_tests/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/src/com/sap/tc/moin/xm/test/pfl/xsd/example/ScenarioFlowDiagramReferencedContent.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ScenarioFlowDiagramReferencedContent
	xmlns:tns="http://www.sap.com/ScenarioFlowDiagramReferencedContent"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sap.com/ScenarioFlowDiagramReferencedContent ../ScenarioFlowDiagramReferencedContent.xsd ">
	<tns:RealizedBusinessScenario ID="300">
		<tns:Title>Plan-Driven Procurement in ERP</tns:Title>
		<tns:RealizedBusinessProcess ID="301">
			<tns:Title>Purchase Request Processing</tns:Title>
			<tns:RealizedBusinessProcessVariant
				ID="302">
				<tns:Title>variant 1"</tns:Title>
			</tns:RealizedBusinessProcessVariant>
			<tns:ProcessComponent ID="303">
				<tns:Title>Process Component 1</tns:Title>
				<tns:DeploymentUnit ID="304">
					<tns:Title>ERP Americas</tns:Title>
				</tns:DeploymentUnit>
			</tns:ProcessComponent>
		</tns:RealizedBusinessProcess>
		<tns:RealizedBusinessProcess ID="305">
			<tns:Title>Purchase Order Processing</tns:Title>
			<tns:RealizedBusinessProcessVariant
				ID="306">
				<tns:Title>variant 1</tns:Title>
			</tns:RealizedBusinessProcessVariant>
			<tns:ProcessComponent ID="307">
				<tns:Title>Process Component 2</tns:Title>
				<tns:DeploymentUnit ID="304">
					<tns:Title>ERP Americas</tns:Title>
				</tns:DeploymentUnit>
			</tns:ProcessComponent>
		</tns:RealizedBusinessProcess>
		<tns:RealizedBusinessProcess ID="309">
			<tns:Title>Inbound Delivery</tns:Title>
			<tns:RealizedBusinessProcessVariant
				ID="310">
				<tns:Title>variant 1</tns:Title>
			</tns:RealizedBusinessProcessVariant>
			<tns:ProcessComponent ID="311">
				<tns:Title>Process Component 3</tns:Title>
				<tns:DeploymentUnit ID="304">
					<tns:Title>ERP Americas</tns:Title>
				</tns:DeploymentUnit>
			</tns:ProcessComponent>
		</tns:RealizedBusinessProcess>
		<tns:RealizedBusinessProcess ID="315">
			<tns:Title>Payment</tns:Title>
			<tns:RealizedBusinessProcessVariant
				ID="316">
				<tns:Title>variant 1</tns:Title>
			</tns:RealizedBusinessProcessVariant>
			<tns:ProcessComponent ID="317">
				<tns:Title>Process Component 3</tns:Title>
				<tns:DeploymentUnit ID="304">
					<tns:Title>ERP Americas</tns:Title>
				</tns:DeploymentUnit>
			</tns:ProcessComponent>
		</tns:RealizedBusinessProcess>
	</tns:RealizedBusinessScenario>
</tns:ScenarioFlowDiagramReferencedContent>
