=== FURCAS-dev/FURCAS/moin_tests/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/src/com/sap/tc/moin/xm/test/pfl/xsd/BusinessProcessCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sap.com/BusinessProcessCatalog"
	xmlns:tns="http://www.sap.com/BusinessProcessCatalog"
	elementFormDefault="qualified">
	<element name="BusinessProcessCatalog" type="tns:BusinessProcessCatalogType">
	</element>
	<complexType name="IDandTitleType">
		<sequence>
			<element name="Title" type="string" />
		</sequence>
		<attribute name="ID" type="string" />
		<attribute name="documentation" type="string"></attribute>
	</complexType>
	<complexType name="BusinessProcessCatalogType">
		<sequence>
			<element name="BusinessArea" type="tns:BusinessAreaType"
				maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>
	<complexType name="BusinessAreaType">
		<complexContent>
			<extension base="tns:IDandTitleType">
				<sequence>
					<element name="ProcessGroup" type="tns:ProcessGroupType"
						maxOccurs="unbounded" minOccurs="0">
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ProcessGroupType">
		<complexContent>
			<extension base="tns:IDandTitleType">
				<sequence>
					<element name="BusinessProcess" type="tns:BusinessProcessType"
						maxOccurs="unbounded" minOccurs="0">
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="BusinessProcessType">
		<complexContent>
			<extension base="tns:IDandTitleType">
				<sequence>
					<element name="RealizedBusinessProcess" type="tns:RealizedBusinessProcessType"
						maxOccurs="unbounded" minOccurs="0">
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="RealizedBusinessProcessType">
		<complexContent>
			<extension base="tns:IDandTitleType">
				<sequence>
					<element name="RealizedBusinessProcessVariant" type="tns:IDandTitleType"
						maxOccurs="unbounded" minOccurs="0">
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="RealizedBusinessProcessVariantType">
		<attribute name="name" type="string"></attribute>
		<attribute name="id" type="string"></attribute>
		<attribute name="documentation" type="string"></attribute>
	</complexType>
</schema>

=== FURCAS-dev/FURCAS/moin_tests/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/src/com/sap/tc/moin/xm/test/pfl/xsd/example/BusinessProcessCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:BusinessProcessCatalog xmlns:tns="http://www.sap.com/BusinessProcessCatalog"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sap.com/BusinessProcessCatalog ../BusinessProcessCatalog.xsd ">
	<tns:BusinessArea ID="100">
		<tns:Title>Procurement</tns:Title>
		<tns:ProcessGroup ID="101">
			<tns:Title>Operational Procurement</tns:Title>
			<tns:BusinessProcess 
				ID="102">
				<tns:Title>Purchase Order Processing</tns:Title>
				<tns:RealizedBusinessProcess
					ID="103">
					<tns:Title>Purchase Order Processing in ERP</tns:Title>
					<tns:RealizedBusinessProcessVariant ID="104">
						<tns:Title>Purchase Order Processing of Direct Materials</tns:Title>
					</tns:RealizedBusinessProcessVariant>
				</tns:RealizedBusinessProcess>
			</tns:BusinessProcess>
		</tns:ProcessGroup>
	</tns:BusinessArea>
	<tns:BusinessArea ID="105">
		<tns:Title>BusinessArea</tns:Title>
		<tns:ProcessGroup ID="106">
			<tns:Title>ProcessGroup</tns:Title>
			<tns:BusinessProcess ID="107">
				<tns:Title>BusinessProcess</tns:Title>
				<tns:RealizedBusinessProcess ID="108">
					<tns:Title>RealizedBusinessProcess</tns:Title>
					<tns:RealizedBusinessProcessVariant
						ID="109">
						<tns:Title>RealizedBusinessProcessVariant</tns:Title>
					</tns:RealizedBusinessProcessVariant>
				</tns:RealizedBusinessProcess>
			</tns:BusinessProcess>
		</tns:ProcessGroup>
	</tns:BusinessArea>
</tns:BusinessProcessCatalog>
