=== FURCAS-dev/FURCAS/moin_tests/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/src/com/sap/tc/moin/xm/test/customexit/mc/testPerson.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://sap.com/moin/xm/test/Person"
	xmlns:tns="http://sap.com/moin/xm/test/Person"
	elementFormDefault="qualified">

	<annotation>
		<documentation>Person Company Address Equipment</documentation>
	</annotation>

	<element name="company">
		<complexType>
			<choice maxOccurs="unbounded">
				<element ref="tns:employee" />
				<element ref="tns:customer" />
			</choice>
		</complexType>

	</element>

	<complexType name="person">
		<sequence>
			<element name="name" type="string"></element>
			<element name="title" type="string" />
			<element ref="tns:address" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<element name="address">
		<complexType>
			<sequence>
				<element name="town" type="string"></element>
				<element name="street">
					<complexType>
						<sequence>
							<element name="name" type="string"></element>
							<element name="number" type="integer"></element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

	<element name="employee">
		<complexType>
			<complexContent>
				<extension base="tns:person">
					<sequence>
						<element ref="tns:equipment" minOccurs="0"
							maxOccurs="unbounded" />
					</sequence>
				</extension>
			</complexContent>
		</complexType>
	</element>

	<element name="customer" type="tns:person"></element>

	<element name="equipment">
		<complexType>
			<attribute name="id" type="string"></attribute>
		</complexType>
	</element>
</schema>

=== FURCAS-dev/FURCAS/moin_tests/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/src/com/sap/tc/moin/xm/test/ps/testPerson.xml
<?xml version="1.0" encoding="UTF-8"?>
<company xmlns="http://sap.com/moin/xm/test/Person"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://sap.com/moin/xm/test/Person testPerson.xsd">

	<employee>
		<name>hugo</name>
		<title>Dr</title>
		<address>
			<town>Munich</town>
			<street>
				<name>Siemensstraße</name>
				<number>12</number>
			</street>
		</address>
		<address>
			<town>Stuttgart</town>
			<street>
				<name>Hellstraße</name>
				<number>1</number>
			</street>
		</address>
		<equipment id="PC"></equipment>
		<equipment id="Laptop"></equipment>
	</employee>
	<customer>
		<name>Müller</name>
		<title>Master of Sience</title>
		<address>
			<town>Frankfurt</town>
			<street>
				<name>Bernauerstraße</name>
				<number>5</number>
			</street>
		</address>
	</customer>
	<employee>
		<name>Berta</name>
		<title>Dipl. Ing.</title>
		<address>
			<town>Berlin</town>
			<street>
				<name>Boschstraße</name>
				<number>2</number>
			</street>
		</address>
		<equipment id="Bycicle"></equipment>
		<equipment id="Car"></equipment>
	</employee>

</company>
